### ISSUE TITLE
Is it still in active development?

### ISSUE THREAD

**Issue by Jasonlhy** [monofon/pandoc-format#1]
Hello, Nice to meet you.
I appreciates your extension which is almost what I want. But sadly It don't work properly on other OS. I wonder if it is still in active development so I can make a pull request in order to port this extension to other OS.

**Comment by monofon** [comment]
Yes, it is. Please send your pull requests.

**Comment by RalphGL** [comment]
...some hints how to use this would be fine. After installing it - what now?
