### ISSUE TITLE
Having a `header includes` causes an issue

### ISSUE THREAD

**Issue by shakram02** [monofon/pandoc-format#2]
Thank you for your effort with the formatter! I'm facing the following issue
I'm having this code on the top of my document 
```Latex
---
header-includes:
- '\hypersetup{colorlinks=true,urlcolor=blue, allbordercolors={0 0 0}}'
...
```
Whenever I format, it adds the following line, even if it already exists from a previous format

```Latex
\hypersetup{colorlinks=true,urlcolor=blue, allbordercolors={0 0 0}}
```

**Comment by monofon** [comment]
Which pandoc version do you use? I cannot reproduce the duplication with pandoc 1.19.2.1.

This is probably a pandoc issue, because the formatter just pipes the entire buffer (or the current selection) through pandoc.

**Comment by shakram02** [comment]
`pandoc 1.16.0.2` it seems like I should update my pandoc then (just installed it using the package manager yesterday), thanks!

**Comment by shakram02** [comment]
I updated it and the issue persists, it's an `.md` file with pieces of `latex`
I'll open an issue at their repo then
