### ISSUE TITLE
Document is corrupted if editor.FormatOnSave is enabled

### ISSUE THREAD

**Issue by NameOfTheDragon** [monofon/pandoc-format#3]
When the `editor.FormatOnSave` setting is set to `true`, then the markdown document is corrupted (with data loss) on saving.

Given the following `settings.json`:

```json
{
    "editor.formatOnSave": true
}
```

and this source document:

    Our query is a little complex so will need some explanation. First, we have the following line:

    ``` CSharp
    var buffers = source.Publish(s => s.BufferByPredicates(p => p == 'P', q => !char.IsDigit(q)));
    ```
    
    This refers to the [RxAscom library][RxAscom]. This is defined using a reference-style hyperlink, below.
    
    [RxAscom]: http://tigra-astronomy.com/reactive-communications-for-ascom "Reactive Communications for ASCOM, project home page"

Upon saving, the document is transformed as follows:

    Our query is a little complex so will need some explanation. First, we have the following line:
    
    ``` {.csharp}
    var buffers = source.Publish(s => s.BufferByPredicates(p => p == 'P', q => !char.IsDigit(q)));
    ```
    
    This refers to the [RxAscom library](http://tigra-astronomy.com/reactive-communications-for-ascom "Reactive Communications for ASCOM, project home page"). This is defined using a reference-style hyperlink, below.

The following issues can be observed:
 - The fenced code blocks have their language changed to something that no longer formats correctly.
 - The reference-style hyperlinks have been inlined, which is not desirable because it creates DRY violations.

**Comment by monofon** [comment]
This is how Pandoc handles code blocks and links by default. There are many options though, see https://pandoc.org/ for details.

You might want to try something like

```
    "pandocFormat.command": "pandoc -t markdown-fenced_code_attributes --reference-links",
```

in your `settings.json`.

**Comment by NameOfTheDragon** [comment]
That does seem to fix the issue. Thank you.

VS-Code pre-filled some options for me, and I left them in and added the ones you suggested from above. So what I actually ended up with was this:

```json
"pandocFormat.command": "pandoc --standalone --atx-headers --wrap=auto --columns=80 -f markdown-auto_identifiers -t markdown-simple_tables-multiline_tables-grid_tables-auto_identifiers-fenced_code_attributes --reference-links"
```
