### ISSUE TITLE
do not remove linebreaks

### ISSUE THREAD

**Issue by maxheld83** [monofon/pandoc-format#4]
It appears that `0.0.3` will delete all single line breaks on every save.

I understand that single linebreaks don't mean anything in pandoc, but it still seems wayyy too aggressive and even dangerous to delete those line breaks.
They are often used to structure a document.

I actually lost a bunch of structure in two documents (not under git, my bad) because of this.

Took me a while to find the offending package, too.

**Comment by monofon** [comment]
Sorry to hear that you lost some of your work.

As far as I know, there is no way to preserve empty lines when using Pandoc to sanitize Markdown. Maybe there are other formatters that can do that.
